server:
  port: 9099

countriesapi:
  baseurl: https://countriesnow.space/api/v0.1


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

##JWT properties
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000